change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"

categories:
  - title: "Documentation"
    labels: ["documentation"]
  - title: "New Features"
    labels: ["enhancement"]
  - title: "Bug Fixes"
    labels: ["bug"]

template: |
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

autolabeler:
  - label: "documentation"
    files: ["**/*.md"]
  - label: "enhancement"
    files: ["src/**/*"]
  - label: "bug"
    files: ["tests/**/*"]
